version: "3"
services:
  muse:
    build: .
    container_name: muse
    restart: unless-stopped
    volumes:
      - /DATA/AppData/muse:/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - BOT_STATUS=${BOT_STATUS}
      - BOT_ACTIVITY_TYPE=${BOT_ACTIVITY_TYPE}
      - BOT_ACTIVITY=${BOT_ACTIVITY}
      - PLAYLIST_APP_URL=${PLAYLIST_APP_URL}
      - HOMELAB_API_URL=${HOMELAB_API_URL}
      - WELCOME_CHANNEL_ID=${WELCOME_CHANNEL_ID}
